# Site settings
title: Hushmail Blog
email: sbs@hushmail.com
description: "Security and privacy"
baseurl: "http://sbrian.github.io/blog"
url: "http://sbrian.github.io"
twitter_username: hushmail

# Build settings
markdown: kramdown
permalink: pretty
