# Site settings
title: Hushmail Blog
email: sbs@hushmail.com
description: "Security and privacy"
baseurl: ""
url: "http://blog.hushmail.com"
twitter_username: hushmail

# Build settings
markdown: kramdown
permalink: pretty
